[project]
name = "recognition"
version = "0.1.0"
description = ""
authors = [
    {name = "Luiz Carlos Cosmi Filho",email = "luizcarloscosmifilho@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"

[tool.poetry]
packages = [{include = "recognition", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
